name: rails github action

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs: 
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
      fail-fast: true
    services: 
      db: 
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rails_github_actions_test
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
    
      - name: check version
        run: ruby -v

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: setup yarn
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install
      
      - name: build and install
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
        
      - name: run test
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPORT: 5432
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}    
        run: |
          bundle exec rake db:migrate
          bundle exec rake test
    
