name: Ci
on: [push]
jobs: 
  test:
    runs-on: ubuntu-latest
    services: 
      db: 
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: ruby --version
