name: Ci
on: [push]
jobs: 
  test:
    runs-on: ubuntu-latest
    services: 
      db: 
        image: postgres:11
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

